version: '3.1'
services:
#  sonarqube:
#    image: sonarqube:7.9.1-community
#    ports:
#      - 9000:9000
##    depends_on:
##      - postgresql_generic
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
##    environment:
##      - sonar.jdbc.username=generic
##      - sonar.jdbc.password=generic
##      - sonar.jdbc.url=jdbc:postgresql://postgresql_generic/generic
#    restart: always
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 32000
#        hard: 40000
#    networks:
#      - asgard

  mysql-docker:
   image: mysql:5.7.28
   environment:
     MYSQL_ROOT_PASSWORD: toor
   ports:
     - 3306:3306
   volumes:
   - ./opt/mysql:/var/lib/mysql
   - ./initdata/initdb.sql:/docker-entrypoint-initdb.d/init.sql
   networks:
      - asgard

  phpmyadmin-docker:
    depends_on:
      - mysql-docker
    image: phpmyadmin/phpmyadmin:edge
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: mysql-docker
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - asgard

networks:
  asgard:
volumes:
  data-postgresql:
  data-postgresql-generic:
  data-artifactory:
  data-bitbucket:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  jenkins-data: