ALTER TABLE TBL_CONTEST_QSO ADD N_ID_DXCC_ENTITY INT NULL;

CREATE TABLE `TBL_DXCC_ENTITY` (
  `N_ID_DXCC_ENTITY` INT NOT NULL,
  `D_ENTITY_CODE` INT NULL,
  `S_ENTITY` VARCHAR(255) NULL,
  `S_CONT` VARCHAR(45) NULL,
  `D_ITU` INT NULL,
  `D_CQ` INT NULL,
  PRIMARY KEY (`id`));

ALTER TABLE TBL_CONTEST_QSO ADD FOREIGN KEY (N_ID_DXCC_ENTITY) REFERENCES TBL_DXCC_ENTITY(N_ID_DXCC_ENTITY);