ALTER TABLE TBL_CONTEST_QSO ADD D_ENTITY_CODE INT NULL;
ALTER TABLE TBL_CONTEST_QSO ADD D_DXCC_NOT_FOUND INT NULL;

CREATE TABLE `CAT_DXCC_ENTITY` (
  `D_ENTITY_CODE` INT NOT NULL,
  `S_ENTITY` VARCHAR(255) NULL,
  `S_CONT` VARCHAR(45) NULL,
  `D_ITU` INT NULL,
  `D_CQ` INT NULL,
  PRIMARY KEY (`D_ENTITY_CODE`));

ALTER TABLE TBL_CONTEST_QSO ADD FOREIGN KEY (D_ENTITY_CODE) REFERENCES CAT_DXCC_ENTITY(D_ENTITY_CODE);

CREATE TABLE `CAT_DXCC_SESSION` (
  `N_ID_DXCC_SESSION` INT NOT NULL,
  `S_KEY` VARCHAR(255) NULL,
  `N_COUNT` INT NULL,
  `D_SUB_EXP` DATETIME NULL,
  `D_GM_TIME` DATETIME NULL,
  `S_REMARK` VARCHAR(255) NULL,
  `S_ERROR` VARCHAR(255) NULL,
  PRIMARY KEY (`N_ID_DXCC_SESSION`));


ALTER TABLE CAT_DXCC_SESSION MODIFY N_ID_DXCC_SESSION INT NOT NULL AUTO_INCREMENT;
