SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `CAT_EMAIL_ERROR` (
  `N_ID_CAT_EMAIL_ERROR` int(11) NOT NULL,
  `N_ID_EDITION` int(11) DEFAULT NULL,
  `S_DESCRIPCION` varchar(255) DEFAULT NULL,
  `S_SUGGESTION_ES` varchar(600) DEFAULT NULL,
  `S_SUGGESTION_EN` varchar(600) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(1, 1, 'EMAIL_WITHOUT_SUBJECT', 'Su correo electrónico no contiene asunto, recuerde incluir el asunto de su correo electrónico (que debería ser solo su indicativo) y reenvie.', 'Your email don\'t contains subject, please remember include the subject of your email (that should be only your callsign) and resend.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(2, 1, 'EMAIL_WITHOUT_ATTACHED_FILES', 'Su correo electrónico no contiene ningún archivo adjunto, recuerde adjuntar su archivo de log y reenvie.', 'Your email don\'t contains any attached file, please remember attach your logfile and resend it.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(3, 1, 'CANT_IDENTIFY_LOGFILE', 'Su correo electrónico contiene algunos archivos adjuntos pero no podemos determinar cuál es su archivo de log, recuerde que su archivo de log debe nombrarse con una extensión .txt, .log o .cbr, cambie el nombre y adjunte su archivo de log y vuelva a envielo.', 'Your email contains some attached files but we cant to determine wich one is your logfile, remember that your log file should be named with a .txt, .log or .cbr extension, please rename and attach your logfile an resend it again.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(4, 1, 'MANY_POSSIBLE_LOGFILE', 'Su correo electrónico contiene algunos archivos adjuntos, pero no podemos determinar cuál es su archivo de log porque mas de uno de ellos podría ser, recuerde que su archivo de log debe nombrarse con una extensión .txt, .log o .cbr, por favor verifique esto y reenvie.', 'Your email contains some attached files but we cant to determine wich one is your logfile because many of that can be, remember that your log file should be named with a .txt, .log or .cbr extension, please rename and attach your logfile an resend again.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(5, 1, 'SUBJECT_NOT_EQUALS_CONTESTLOG_CALLSIGN', 'El asunto en su correo electrónico no es igual al indicativo en su log (que fue tomado de su archivo de log) recuerde que su asunto debe ser igual a su indicativo en su log Por favor, corríjalo y reenvíelo.', 'The subject on your email is not equals than the callsign on your log (that was taked from your logfile), remember that your subject should be equals than your callsign on your log. Please, correct it and resend it.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(6, 1, 'EMAIL_WITHOUT_CONTSTLOG', 'Pudimos encontrar un posible archivo de log pero no pudimos analizarlo. Compruebe que su archivo de log se generó en formato cabrillo y vuelva a enviarlo.', 'We were able to find your file but we can\'t to parse it into a log. Please check that your logfile was generated on cabrillo format and resend it.');
INSERT INTO `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`, `N_ID_EDITION`, `S_DESCRIPCION`, `S_SUGGESTION_ES`, `S_SUGGESTION_EN`) VALUES(7, 1, 'SUBJECT_WITH_MORE_THAN_ONE_WORD', 'El asunto de su correo contiene más de una palabra, recuerde incluir el asunto de su correo electrónico (que debería ser solo su indicativo) y vuelva a enviarlo.', 'Your email subject contains more than one word please remember include the subject of your email (that should be only your callsign) and resend it.');

CREATE TABLE `CAT_EMAIL_STATUS` (
  `N_ID_EMAIL_STATUS` int(11) NOT NULL,
  `S_STATUS` varchar(255) DEFAULT NULL,
  `S_DESCRIPTION` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(1, 'RECIVED', 'When email has recived is setted with this status');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(2, 'IGNORED', 'The subject contains the word \'Undelivered\' because that this email will be ignored');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(3, 'IDENTIFIED', 'The email contains a file identified as a logfile');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(4, 'NO_IDENTIFIED', 'The logfile cannot be identified as a logfile');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(5, 'PARSED', 'The logfile was succesfully parsed into log and qsos registers');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(6, 'NO_PARSED', 'The logfile cannot exists or cannot be parsed into log and qsos registers');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(7, 'VERIFIED', 'Email verified to check errors');
INSERT INTO `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`, `S_STATUS`, `S_DESCRIPTION`) VALUES(8, 'ANSWERED', 'Email answered (with successfully or error message)');

CREATE TABLE `REL_EMAIL_EMAIL_ERROR` (
  `N_ID_CAT_EMAIL_ERROR` int(11) NOT NULL,
  `N_ID_EMAIL` int(11) NOT NULL,
  `D_FECHA_REGISTRO` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `REL_USER_ROLE` (
  `N_ID_ROLE` int(11) NOT NULL,
  `N_ID_USER` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `REL_USER_ROLE` (`N_ID_ROLE`, `N_ID_USER`) VALUES(1, 1);

CREATE TABLE `TBL_ATTACHED_FILE` (
  `N_ID_ATTACHED_FILE` int(11) NOT NULL,
  `N_ID_EMAIL` int(11) DEFAULT NULL,
  `S_FILENAME` varchar(255) DEFAULT NULL,
  `S_CONTENT_TYPE` varchar(255) DEFAULT NULL,
  `N_LENGHT` int(11) DEFAULT NULL,
  `S_MD5_HASH` varchar(255) DEFAULT NULL,
  `S_PATH` varchar(255) DEFAULT NULL,
  `D_ISLOGFILE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBL_CONTEST` (
  `N_ID_CONTEST` int(11) NOT NULL,
  `S_DESCRIPTION` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `TBL_CONTEST` (`N_ID_CONTEST`, `S_DESCRIPTION`) VALUES(1, 'International RTTY Contest FMRE');

CREATE TABLE `TBL_CONTEST_LOG` (
  `N_ID_CONTEST_LOG` int(11) NOT NULL,
  `S_ADDRESS` varchar(255) DEFAULT NULL,
  `S_ADDRESS_CITY` varchar(255) DEFAULT NULL,
  `S_ADDRESS_COUNTRY` varchar(255) DEFAULT NULL,
  `S_ADDRESS_STATE_PROVINCE` varchar(255) DEFAULT NULL,
  `S_CALLSIGN` varchar(255) DEFAULT NULL,
  `S_CATEGORY_BAND` varchar(255) DEFAULT NULL,
  `S_CATEGORY_MODE` varchar(255) DEFAULT NULL,
  `S_CATEGORY_OPERATOR` varchar(255) DEFAULT NULL,
  `S_CATEGORY_POWER` varchar(255) DEFAULT NULL,
  `D_CLAIMED_SCORE` int(11) DEFAULT NULL,
  `S_CLUB` varchar(255) DEFAULT NULL,
  `S_CONTEST` varchar(255) DEFAULT NULL,
  `S_CREATED_BY` varchar(255) DEFAULT NULL,
  `S_EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `S_NAME` varchar(255) DEFAULT NULL,
  `S_OPERATORS` varchar(255) DEFAULT NULL,
  `S_SOAPBOX` varchar(255) DEFAULT NULL,
  `D_IS_CHECKLOG` int(11) DEFAULT NULL,
  `N_ID_EMAIL` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBL_CONTEST_QSO` (
  `N_ID_CONTEST_QSO` int(11) NOT NULL,
  `S_CALLSIGN_EMISOR` varchar(255) DEFAULT NULL,
  `S_CALLSIGN_RECEPTOR` varchar(255) DEFAULT NULL,
  `D_DATETIME` datetime DEFAULT NULL,
  `S_EXCHANGE_EMMITED` varchar(255) DEFAULT NULL,
  `S_EXCHANGE_RECEIVED` varchar(255) DEFAULT NULL,
  `N_FREQUENCY` int(11) DEFAULT NULL,
  `S_CATEGORY_OPERATOR` varchar(255) DEFAULT NULL,
  `S_MODE` varchar(255) DEFAULT NULL,
  `S_RST_EMMITED` varchar(255) DEFAULT NULL,
  `S_RST_RECEIVED` varchar(255) DEFAULT NULL,
  `N_ID_CONTEST_LOG` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBL_EDITION` (
  `N_ID_EDITION` int(11) NOT NULL,
  `N_ID_CONTEST` int(11) DEFAULT NULL,
  `S_DESCRIPTION` varchar(255) DEFAULT NULL,
  `N_YEAR` int(11) DEFAULT NULL,
  `T_START_UTC` datetime DEFAULT NULL,
  `T_END_UTC` datetime DEFAULT NULL,
  `N_ID_EMAIL_START` int(11) DEFAULT NULL,
  `N_ID_EMAIL_END` int(11) DEFAULT NULL,
  `N_ACTIVE` bit(1) DEFAULT NULL,
  `S_TEMPLATE` varchar(255) DEFAULT NULL,
  `S_QSO_PARSER_IMPL` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `TBL_EDITION` (`N_ID_EDITION`, `N_ID_CONTEST`, `S_DESCRIPTION`, `N_YEAR`, `T_START_UTC`, `T_END_UTC`, `N_ID_EMAIL_START`, `N_ID_EMAIL_END`, `N_ACTIVE`, `S_TEMPLATE`, `S_QSO_PARSER_IMPL`) VALUES(1, 1, 'Edición 2020', 2019, '2011-08-05 00:00:00', '2011-08-15 00:00:00', 3529, NULL, b'1', 'email_template_rtty_2020', 'qsoParserRtty2020ServiceImpl');

CREATE TABLE `TBL_EMAIL` (
  `N_ID_EMAIL` int(11) NOT NULL,
  `N_EMAIL_COUNT` int(11) DEFAULT NULL,
  `N_ID_EDITION` int(11) DEFAULT NULL,
  `S_RECIPIENTS_FROM_NAME` varchar(255) DEFAULT NULL,
  `S_RECIPIENTS_FROM_ADDRESS` varchar(255) DEFAULT NULL,
  `D_RECEIVED_DATE` datetime DEFAULT NULL,
  `S_RECIPIENTS_TO` varchar(255) DEFAULT NULL,
  `D_SENT_DATE` datetime DEFAULT NULL,
  `S_SUBJECT` varchar(255) DEFAULT NULL,
  `N_ID_EMAIL_STATUS` int(11) DEFAULT NULL,
  `VERIFIED_AT` datetime DEFAULT NULL,
  `ANSWERED_AT` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TBL_EMAIL_ACCOUNT` (
  `N_ID_EMAIL_ACCOUNT` int(11) NOT NULL,
  `N_ID_CONTEST` int(11) DEFAULT NULL,
  `S_IN_HOST` varchar(255) DEFAULT NULL,
  `S_OUT_HOST` varchar(255) DEFAULT NULL,
  `S_EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `S_USERNAME` varchar(255) DEFAULT NULL,
  `S_PASSWORD` varchar(255) DEFAULT NULL,
  `N_IN_PORT` int(11) DEFAULT NULL,
  `N_OUT_PORT` int(11) DEFAULT NULL,
  `S_REPLY_TO_NAME` varchar(255) DEFAULT NULL,
  `S_REPLY_TO_EMAIL` varchar(255) DEFAULT NULL,
  `SUCCESSFULLY_RESPONSE_MSG` varchar(255) DEFAULT NULL,
  `ERROR_RESPONSE_MSG` varchar(255) DEFAULT NULL,
  `S_SMTP_PROPERTIES` varchar(600) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `TBL_EMAIL_ACCOUNT` (`N_ID_EMAIL_ACCOUNT`, `N_ID_CONTEST`, `S_IN_HOST`, `S_OUT_HOST`, `S_EMAIL_ADDRESS`, `S_USERNAME`, `S_PASSWORD`, `N_IN_PORT`, `N_OUT_PORT`, `S_REPLY_TO_NAME`, `S_REPLY_TO_EMAIL`, `SUCCESSFULLY_RESPONSE_MSG`, `ERROR_RESPONSE_MSG`, `S_SMTP_PROPERTIES`) VALUES(1, 1, 'imap.fmre.mx', 'just101.justhost.com', 'rtty@fmre.mx', 'rtty@fmre.mx', 'aJX24Yxiljgg16SmL6YJyA==', 993, 465, 'XE1EE', 'rttymanager@fmre.mx', 'Correo recibido correctamente / Email received correctly', 'Email recibido con errores / Email received with errors', 'mail.transport.protocol:smtp;mail.smtp.auth:true;mail.debug:true;mail.smtp.socketFactory.port:465;mail.smtp.socketFactory.class:javax.net.ssl.SSLSocketFactory;mail.smtp.socketFactory.fallback:false');

CREATE TABLE `TBL_ROLES` (
  `N_ID_ROLE` int(11) NOT NULL,
  `S_ROLE` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `TBL_ROLES` (`N_ID_ROLE`, `S_ROLE`) VALUES(1, 'USER');

CREATE TABLE `TBL_USERS` (
  `N_ID_USER` int(11) NOT NULL,
  `S_EMAIL` varchar(255) DEFAULT NULL,
  `S_PASSWORD` varchar(255) DEFAULT NULL,
  `S_NAME` varchar(255) DEFAULT NULL,
  `S_LAST_NAME` varchar(255) DEFAULT NULL,
  `B_ACTIVE` bit(1) DEFAULT b'0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `TBL_USERS` (`N_ID_USER`, `S_EMAIL`, `S_PASSWORD`, `S_NAME`, `S_LAST_NAME`, `B_ACTIVE`) VALUES(1, 'admin@admin.com', '$2a$10$jLpHkSywOB9WhE5Se3nLH.KfC2Pi6H7wHblaya0xx34nK970o6qYa', 'adminname', 'adminlastname', b'1');


ALTER TABLE `CAT_EMAIL_ERROR`
  ADD PRIMARY KEY (`N_ID_CAT_EMAIL_ERROR`),
  ADD KEY `CONSTRAINT_FK_CAT_EMAIL_ERROR` (`N_ID_EDITION`);

ALTER TABLE `CAT_EMAIL_STATUS`
  ADD PRIMARY KEY (`N_ID_EMAIL_STATUS`);

ALTER TABLE `REL_EMAIL_EMAIL_ERROR`
  ADD PRIMARY KEY (`N_ID_CAT_EMAIL_ERROR`,`N_ID_EMAIL`),
  ADD KEY `CONSTRAINT_FK_REL_EMAIL_EMAIL_ERROR_TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `REL_USER_ROLE`
  ADD PRIMARY KEY (`N_ID_ROLE`,`N_ID_USER`),
  ADD KEY `CONSTRAINT_FK_USER_ROLE_USER` (`N_ID_USER`);

ALTER TABLE `TBL_ATTACHED_FILE`
  ADD PRIMARY KEY (`N_ID_ATTACHED_FILE`),
  ADD KEY `CONSTRAINT_FK_TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `TBL_CONTEST`
  ADD PRIMARY KEY (`N_ID_CONTEST`);

ALTER TABLE `TBL_CONTEST_LOG`
  ADD PRIMARY KEY (`N_ID_CONTEST_LOG`),
  ADD KEY `CONSTRAINT_FK_TBL_CONTEST_LOG_TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `TBL_CONTEST_QSO`
  ADD PRIMARY KEY (`N_ID_CONTEST_QSO`),
  ADD KEY `CONSTRAINT_FK_TBL_CONTEST_QSO_TBL_CONTEST_LOG` (`N_ID_CONTEST_LOG`);

ALTER TABLE `TBL_EDITION`
  ADD PRIMARY KEY (`N_ID_EDITION`),
  ADD KEY `CONSTRAINT_FK_EDITION_CONTEST` (`N_ID_CONTEST`);

ALTER TABLE `TBL_EMAIL`
  ADD PRIMARY KEY (`N_ID_EMAIL`),
  ADD KEY `CONSTRAINT_FK_TBL_EDITION` (`N_ID_EDITION`),
  ADD KEY `CONSTRAINT_FK_CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`);

ALTER TABLE `TBL_EMAIL_ACCOUNT`
  ADD PRIMARY KEY (`N_ID_EMAIL_ACCOUNT`),
  ADD KEY `CONSTRAINT_FK_EMAIL_CONTEST` (`N_ID_CONTEST`);

ALTER TABLE `TBL_ROLES`
  ADD PRIMARY KEY (`N_ID_ROLE`);

ALTER TABLE `TBL_USERS`
  ADD PRIMARY KEY (`N_ID_USER`);


ALTER TABLE `CAT_EMAIL_ERROR`
  MODIFY `N_ID_CAT_EMAIL_ERROR` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

ALTER TABLE `CAT_EMAIL_STATUS`
  MODIFY `N_ID_EMAIL_STATUS` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

ALTER TABLE `TBL_ATTACHED_FILE`
  MODIFY `N_ID_ATTACHED_FILE` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_CONTEST`
  MODIFY `N_ID_CONTEST` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `TBL_CONTEST_LOG`
  MODIFY `N_ID_CONTEST_LOG` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_CONTEST_QSO`
  MODIFY `N_ID_CONTEST_QSO` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_EDITION`
  MODIFY `N_ID_EDITION` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `TBL_EMAIL`
  MODIFY `N_ID_EMAIL` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_ROLES`
  MODIFY `N_ID_ROLE` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `TBL_USERS`
  MODIFY `N_ID_USER` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;


ALTER TABLE `CAT_EMAIL_ERROR`
  ADD CONSTRAINT `CONSTRAINT_FK_CAT_EMAIL_ERROR` FOREIGN KEY (`N_ID_EDITION`) REFERENCES `TBL_EDITION` (`N_ID_EDITION`);

ALTER TABLE `REL_EMAIL_EMAIL_ERROR`
  ADD CONSTRAINT `CONSTRAINT_FK_REL_EMAIL_EMAIL_ERROR_CAT_EMAIL_ERROR` FOREIGN KEY (`N_ID_CAT_EMAIL_ERROR`) REFERENCES `CAT_EMAIL_ERROR` (`N_ID_CAT_EMAIL_ERROR`),
  ADD CONSTRAINT `CONSTRAINT_FK_REL_EMAIL_EMAIL_ERROR_TBL_EMAIL` FOREIGN KEY (`N_ID_EMAIL`) REFERENCES `TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `REL_USER_ROLE`
  ADD CONSTRAINT `CONSTRAINT_FK_USER_ROLE_ROLE` FOREIGN KEY (`N_ID_ROLE`) REFERENCES `TBL_ROLES` (`N_ID_ROLE`),
  ADD CONSTRAINT `CONSTRAINT_FK_USER_ROLE_USER` FOREIGN KEY (`N_ID_USER`) REFERENCES `TBL_USERS` (`N_ID_USER`);

ALTER TABLE `TBL_ATTACHED_FILE`
  ADD CONSTRAINT `CONSTRAINT_FK_TBL_EMAIL` FOREIGN KEY (`N_ID_EMAIL`) REFERENCES `TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `TBL_CONTEST_LOG`
  ADD CONSTRAINT `CONSTRAINT_FK_TBL_CONTEST_LOG_TBL_EMAIL` FOREIGN KEY (`N_ID_EMAIL`) REFERENCES `TBL_EMAIL` (`N_ID_EMAIL`);

ALTER TABLE `TBL_CONTEST_QSO`
  ADD CONSTRAINT `CONSTRAINT_FK_TBL_CONTEST_QSO_TBL_CONTEST_LOG` FOREIGN KEY (`N_ID_CONTEST_LOG`) REFERENCES `TBL_CONTEST_LOG` (`N_ID_CONTEST_LOG`);

ALTER TABLE `TBL_EDITION`
  ADD CONSTRAINT `CONSTRAINT_FK_EDITION_CONTEST` FOREIGN KEY (`N_ID_CONTEST`) REFERENCES `TBL_CONTEST` (`N_ID_CONTEST`);

ALTER TABLE `TBL_EMAIL`
  ADD CONSTRAINT `CONSTRAINT_FK_CAT_EMAIL_STATUS` FOREIGN KEY (`N_ID_EMAIL_STATUS`) REFERENCES `CAT_EMAIL_STATUS` (`N_ID_EMAIL_STATUS`),
  ADD CONSTRAINT `CONSTRAINT_FK_TBL_EDITION` FOREIGN KEY (`N_ID_EDITION`) REFERENCES `TBL_EDITION` (`N_ID_EDITION`);

ALTER TABLE `TBL_EMAIL_ACCOUNT`
  ADD CONSTRAINT `CONSTRAINT_FK_EMAIL_CONTEST` FOREIGN KEY (`N_ID_CONTEST`) REFERENCES `TBL_CONTEST` (`N_ID_CONTEST`);
SET FOREIGN_KEY_CHECKS=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
